-- DISTINCT
SELECT 
DISTINCT FUNCIONARIO.Salario 
FROM FUNCIONARIO;

-- WHERE
SELECT * FROM FUNCIONARIO 
WHERE Pnome = 'João';

-- AND
SELECT * 
FROM FUNCIONARIO 
WHERE Sexo = 'M' AND Salario >= 30000;

--OR
SELECT * 
FROM FUNCIONARIO
WHERE Endereco LIKE '%São Paulo%'
OR Endereco LIKE '%Curitiba%';

--NOT
SELECT * 
FROM FUNCIONARIO
WHERE NOT Endereco LIKE '%São Paulo%';

-- ORDER BY
SELECT * 
FROM FUNCIONARIO
ORDER BY Salario DESC;

--IS NULL
SELECT *
FROM FUNCIONARIO
WHERE Cpf_supervisor IS NULL;

--IS NOT NULL
SELECT *
FROM FUNCIONARIO
WHERE Cpf_supervisor IS NOT NULL;

--TOP
SELECT TOP 3 * 
FROM FUNCIONARIO
ORDER BY Salario DESC;

--MIN()
SELECT MIN(Salario)
FROM FUNCIONARIO;

SELECT *
FROM FUNCIONARIO
WHERE Salario = (
	SELECT MIN(Salario)
	FROM FUNCIONARIO
);

DECLARE @Salario_Min DECIMAL(10,2);

/*

SELECT @Salario_Min = MIN(FUNCIONARIO.Salario)
FROM FUNCIONARIO;
*/

SET @Salario_Min = (SELECT MIN(Salario)
					FROM FUNCIONARIO);

SELECT *
FROM FUNCIONARIO
WHERE Salario = @Salario_Min;

-- MAX()
SELECT *
FROM FUNCIONARIO
WHERE Salario = (
	SELECT MAX(Salario)
	FROM FUNCIONARIO
);

--COUNT()
SELECT COUNT (FUNCIONARIO.Cpf)
FROM FUNCIONARIO;

-- AVG
DECLARE @Salario_AVG DECIMAL(10,2)
SET @Salario_AVG  = (SELECT AVG(Salario)
					FROM FUNCIONARIO);
						
DECLARE @Salario_MAX DECIMAL(10,2)
SET @Salario_Max = (SELECT MAX(Salario)
					FROM FUNCIONARIO);
PRINT 'A difereça é: ' + CAST((@Salario_MAX - @Salario_AVG) AS VARCHAR (10));

--LIKE
SELECT * 
FROM FUNCIONARIO
WHERE Datanasc LIKE '_____06%';

-- IN
SELECT *
FROM FUNCIONARIO
WHERE Salario IN (25000,30000);

SELECT Cpf 
FROM FUNCIONARIO
WHERE Pnome = 'Fernando';


SELECT Pnr, Horas
FROM TRABALHA_EM
WHERE Fcpf = '33344555587';

DECLARE @Cpf_Funcionario VARCHAR(11);
SET @Cpf_Funcionario =	(SELECT Cpf 
						FROM FUNCIONARIO
						WHERE Pnome = 'Fernando');
SELECT DISTINCT CONCAT(F.Pnome,' ', F.Minicial,' ', F.Unome) AS 'Nome'
FROM TRABALHA_EM AS TE, FUNCIONARIO AS F
WHERE CONCAT(Pnr, Horas) IN (SELECT CONCAT(Pnr, Horas)
							FROM TRABALHA_EM
							WHERE Fcpf =(@Cpf_Funcionario))
AND Fcpf <> @Cpf_Funcionario
AND TE.Fcpf = F.Cpf;


SELECT f.*
FROM FUNCIONARIO f
JOIN TRABALHA_EM t ON f.Cpf = t.Fcpf
WHERE t.Pnr IN (SELECT Pnr FROM TRABALHA_EM WHERE Fcpf = '33344555587')
AND t.Horas IN (SELECT Horas FROM TRABALHA_EM WHERE Fcpf = '33344555587');


SELECT DISTINCT F.Pnome, F.Minicial, F.Unome
FROM TRABALHA_EM AS T1, TRABALHA_EM AS T2, FUNCIONARIO AS F
WHERE T1.Pnr = T2.Pnr
AND T1.Horas = T2.Horas
AND T2.Fcpf = (	SELECT Cpf 
				FROM FUNCIONARIO
				WHERE Pnome = 'Fernando')
AND T1.Fcpf <> (SELECT Cpf 
				FROM FUNCIONARIO
				WHERE Pnome = 'Fernando')
AND T1.Fcpf = F.Cpf;

SELECT DISTINCT T1.Fcpf
FROM TRABALHA_EM AS T1
JOIN TRABALHA_EM AS T2
	ON T1.Pnr = T2.Pnr
	AND T1.Horas = T2.Horas
WHERE T2.Fcpf = '33344555587';

-- JOIN
INSERT INTO FUNCIONARIO (Pnome, Minicial, Unome, Cpf, Datanasc, Endereco, Sexo, Salario, Cpf_supervisor, Dnr)
VALUES ('Carlos', 'M', 'Ferreira', '12312312311', '1980-02-15', 'Av. Paulista, 1000, São Paulo, SP', 'M', 45000, NULL, NULL);

INSERT INTO FUNCIONARIO (Pnome, Minicial, Unome, Cpf, Datanasc, Endereco, Sexo, Salario, Cpf_supervisor, Dnr)
VALUES ('Mariana', 'L', 'Gomes', '32132132122', '1985-06-22', 'Rua das Acácias, 500, Rio de Janeiro, RJ', 'F', 42000, NULL, NULL);

INSERT INTO FUNCIONARIO (Pnome, Minicial, Unome, Cpf, Datanasc, Endereco, Sexo, Salario, Cpf_supervisor, Dnr)
VALUES ('Pedro', 'A', 'Silva', '65465465433', '1990-11-10', 'Rua da Praia, 200, Salvador, BA', 'M', 47000, NULL, NULL);

INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('Vendas', 6);

INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('Recursos Humanos', 7);

INSERT INTO DEPARTAMENTO (Dnome, Dnumero)
VALUES ('TI', 8);

--LEFT JOIN 
SELECT 
    FUNCIONARIO.Pnome,
    FUNCIONARIO.Minicial,
    FUNCIONARIO.Unome,
    FUNCIONARIO.Cpf,
    FUNCIONARIO.Datanasc,
    FUNCIONARIO.Endereco,
    FUNCIONARIO.Sexo,
    FUNCIONARIO.Salario,
    FUNCIONARIO.Cpf_supervisor,
    FUNCIONARIO.Dnr,
    DEPARTAMENTO.Dnome
FROM 
    FUNCIONARIO
LEFT JOIN 
    DEPARTAMENTO 
ON 
    FUNCIONARIO.Dnr = DEPARTAMENTO.Dnumero;

--RIGHT JOIN
SELECT 
    FUNCIONARIO.Pnome,
    FUNCIONARIO.Minicial,
    FUNCIONARIO.Unome,
    FUNCIONARIO.Cpf,
    FUNCIONARIO.Datanasc,
    FUNCIONARIO.Endereco,
    FUNCIONARIO.Sexo,
    FUNCIONARIO.Salario,
    FUNCIONARIO.Cpf_supervisor,
    FUNCIONARIO.Dnr,
    DEPARTAMENTO.Dnome
FROM 
    FUNCIONARIO
RIGHT JOIN 
    DEPARTAMENTO 
ON 
    FUNCIONARIO.Dnr = DEPARTAMENTO.Dnumero;

--FULL JOIN
SELECT 
    FUNCIONARIO.Pnome,
    FUNCIONARIO.Minicial,
    FUNCIONARIO.Unome,
    FUNCIONARIO.Cpf,
    FUNCIONARIO.Datanasc,
    FUNCIONARIO.Endereco,
    FUNCIONARIO.Sexo,
    FUNCIONARIO.Salario,
    FUNCIONARIO.Cpf_supervisor,
    FUNCIONARIO.Dnr,
    DEPARTAMENTO.Dnome
FROM 
    FUNCIONARIO
FULL JOIN 
    DEPARTAMENTO 
ON 
    FUNCIONARIO.Dnr = DEPARTAMENTO.Dnumero;


